[package]
name = "server"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "protos"
path = "src/protos/mod.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
futures = "0.3.30"
grpcio = { version = "0.13.0", features = ["openssl"]}
protobuf = "3.3.0"

[build-dependencies]
protoc-grpcio = "3.0.0"
