[package]
name = "bloomfilter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
num = "0.4.1"
sha2 = "0.10.8"
